### ISSUE TITLE
GUI: minimize to system tray when closed

### ISSUE THREAD

**Issue by abhsag24** [NITDgpOS/UIP#197]

**Comment by nkprince007** [comment]
How exactly do we tackle this? GDE and Unity don't have system tray, right?

**Comment by abhsag24** [comment]
yes neither do KDE and windows and Mac, but i guess there are thrid party services that do this, we've got to search

**Comment by abhsag24** [comment]
http://docs.wxwidgets.org/2.8.8/wx_wxtaskbaricon.html#wxtaskbaricon is a nice way if someone wants a starting point

**Comment by nkprince007** [comment]
I think this serves even better, bro@abhsag24

http://candidtim.github.io/appindicator/2014/09/13/ubuntu-appindicator-step-by-step.html

**Comment by abhsag24** [comment]
@nkprince007 the previous one was windows only i think. I think yu'll have to implement all of these differently

**Comment by nkprince007** [comment]
since I'm on kde I can't proceed any further on this

**Comment by Aniq55** [comment]
@nkprince007 I am trying to get Gtk in python but I am having problems. Any help?

**Comment by Aniq55** [comment]
![img_20170126_164647](https://cloud.githubusercontent.com/assets/20151858/22329577/de90759e-e3e7-11e6-952b-893b34b1534f.jpg)

Is this design alright? @nkprince007 @abhsag24

**Comment by abhsag24** [comment]
@Aniq55 yes this looks good for the basic case might want to add a menu to maximize and bring back the normal GUI ?

**Comment by Aniq55** [comment]
Yeah Cool @abhsag24

**Comment by nkprince007** [comment]
@Aniq55 please wait until the Event starts, you shouldn't be contributing before time :P

**CC** @abhsag24 @Aniq55

**Comment by abhsag24** [comment]
Nah it's okay. GSoC has the same rule you can make prototypes.

**Comment by Aniq55** [comment]
I haven't started contributing, just checking and discussing the design. @nkprince007

**Comment by Aniq55** [comment]
Link for windows:
http://www.brunningonline.net/simon/blog/archives/SysTrayIcon.py.html

**Comment by abhsag24** [comment]
#374
