### ISSUE TITLE
Use pyinstaller to create executables

### ISSUE THREAD

**Issue by abhsag24** [NITDgpOS/UIP#205]

**Comment by nkprince007** [comment]
Does this cover windows section bro?

**Comment by hackrush01** [comment]
That's what I had to ask. Are we creating only windows executables?

**Comment by abhsag24** [comment]
Nope executables for all

**Comment by hackrush01** [comment]
Okay

**Comment by nkprince007** [comment]
Btw @abhsag24 what's the mobile client you're using for GitHub?

**Comment by abhsag24** [comment]
None replying through emails :P

**Comment by hackrush01** [comment]
I am relatively new to python but I would really like to work on this issue. Can someone point me to some resource on how to get started. Because what I saw till now is that pyInstaller needs a predefined 'entry point'. But in our case our entry point is `UIP` which then calls `main` of `uiplib/UIP.py` according to the argument passed. And I could not find a way to do it with pyInstaller.

**Comment by abhsag24** [comment]
@hackrush01 i'm not entirely sure about pyinstaller as well. Part of the solution is to understand and research how pyinstaller works actually and how to best use it for our usecase.

**Comment by hackrush01** [comment]
Also is there a way in python to check the flow of the program? As reading the code is not the most efficient way of doing that. IMO.

**Comment by nkprince007** [comment]
Reading code is **the** best way to do that @hackrush01

**Comment by nkprince007** [comment]
@hackrush01 You could start with `pyinstaller --onefile uiplib/UIP.py` Which bundles the output into `dist` directory, but be sure to clean `build` and `dist` before you try to create binaries

**Comment by hackrush01** [comment]
Can someone please test if the executable is working? My OS is giving me problems.

**Comment by abhsag24** [comment]
that's a pretty weird error

**Comment by hackrush01** [comment]
Yeah. I tried pip installing urllib3 and requests
No avail.

**Comment by nkprince007** [comment]
I've given a try too. It's a problem with the bundler, some imports are not being analyzed by the automatic analysis, that's what is giving the error.

**Comment by abhsag24** [comment]
@hackrush01 for me on windows it just opens and then closes no error no messages. Did you go through hidden imports btw?

**Comment by nkprince007** [comment]
I've the same thing too. On Arch Linux.

**Comment by hackrush01** [comment]
What are hidded imports?

**Comment by abhsag24** [comment]
@hackrush01 yup, i dont know conceptually what they are :P , was just going through why pyinstaller ight be fauling

**Comment by hackrush01** [comment]
Please check. It's working in mine.
And I'll upload to drive/dropbox later. Right now I'll use this.

**Comment by nkprince007** [comment]
@hackrush01 Still no luck here, with your commit.. 
Check output [here](http://pastebin.com/QmpP9Pgs)

**Comment by abhsag24** [comment]
@hackrush01 works on ubuntu 16.04 :D

**Comment by nemaniarjun** [comment]
Close if done?

**Comment by abhsag24** [comment]
@nemaniarjun problem is we need to have it so that we can automate this or atleast make it easier to create executables.

**Comment by abhsag24** [comment]
We're moving from more of a software to a library so let's move a way from issues like these
