### ISSUE TITLE
Make GUI default

### ISSUE THREAD

**Issue by abhsag24** [NITDgpOS/UIP#283]
Before this make sure
- [ ] We can start scheduling wallpapers from within UI
- [ ] We can minimize to system tray.

**Comment by nemaniarjun** [comment]
We also need GUI CI tests before we can make it default.

**Comment by abhsag24** [comment]
@nemaniarjun i'm not sure about that, i'm all for for testing helper methods in GUI but not the actual code for creations of button etc. Like we don't test HTML in websites right?

**Comment by nemaniarjun** [comment]
I just meant we should add tests for everything that can be tests (sanely) :P

**Comment by abhsag24** [comment]
Definitely not since #374
