### ISSUE TITLE
Update the screenshots in the README (current GUI)

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/UIP#297]
(newcomer)

**Comment by jayantsaraf** [comment]
i want to contribute to this issue. can you please tell me which screenshots i need to include?

**Comment by Aniq55** [comment]
We need three screenshots: Windows, Linux and Mac. In Linux we have the system tray as well as the main window. So we'll require screenshots of both of these. in Windows and Mac however, just the main window would do. Make sure the wallpaper shown in the window is applied and then take the screenshot.

**Comment by jayantsaraf** [comment]
how can i run the project on mac and linux because i am on windows

**Comment by Aniq55** [comment]
Then just do it for Windows, put the  screenshot in the screenshots folder
and when some other people contribute for other platforms, you can change
the file reference in the readme

**Comment by abhsag24** [comment]
no need deprecating GUI :P lets post screenshots with glyphicons when we have the, closing this till then
