### ISSUE TITLE
Remove GUI

### ISSUE THREAD

**Issue by abhsag24** [NITDgpOS/UIP#374]
As per our new direction [here](https://gitter.im/NIT-dgp/General?at=5a2142663a80a84b5ba3d660) we dont need it. So lets just completely remove it :P

**Comment by nkprince007** [comment]
@abhsag24 what about the existing stuff. Like the cropping, blur, etc.

**Comment by abhsag24** [comment]
@nkprince007 let's try and integrate them in the new structure
